--VIEWS
--VIEW FOR CURRENT_TENANTS
create or replace view current_tenant_view
as 
select landlord.landlord_id, landlord.landlord_first_name, landlord.landlord_last_name,apartment.apartment_id, customers.customer_first_name, 
customers.customer_last_name,lease_details.lease_status from landlord
join apartment
ON landlord.landlord_id = apartment.landlord_id
JOIN
lease_details
on 
apartment.apartment_id= lease_details.apartment_id
join
CUSTOMERS
ON lease_details.lease_id = customers.lease_id
order by landlord.landlord_first_name;

SELECT * FROM current_tenant_view;

--VIEW FOR APARTMENT-DETAILS ACCORDING TO PRICE RANGE
CREATE OR REPLACE VIEW APARTMENT_DETAILS
AS
SELECT APARTMENT.APARTMENT_NUMBER, APARTMENT.APARTMENT_STREET_NAME AS STREET, APARTMENT_NEIGHBOURHOOD AS NEIGHBOURHOOD, APARTMENT.TOTAL_AREA, 
APARTMENT.MONTHLY_RENT, APARTMENT_TYPE.LOCALITY, APARTMENT_TYPE.NUMBER_OF_ROOMS, APARTMENT_TYPE.NUMBER_OF_BATHS
FROM APARTMENT JOIN APARTMENT_TYPE ON APARTMENT.APARTMENT_TYPE_ID=APARTMENT_TYPE.APARTMENT_TYPE_ID
WHERE MONTHLY_RENT BETWEEN &MIN_RANGE AND &MAX_RANGE;

SELECT * FROM APARTMENT_DETAILS;

--VIEW FOR APARTMENT-DETAILS ACCORDING TO UTILITIES INCLUDED IN RENT
CREATE OR REPLACE VIEW APARTMENT_UTILITY_DETAILS AS
SELECT 'Apartment-' || APARTMENT.APARTMENT_ID ||' '||APARTMENT.APARTMENT_NUMBER||' '||'at'||' '||APARTMENT.APARTMENT_STREET_NAME||' ' || 'has'||' ' || UTILITY.UTILITY_NAME ||' ' ||
'included in rent' ||'(LOCALITY-' || APARTMENT_TYPE.LOCALITY ||')' AS UTILITY_DETAILS
FROM APARTMENT JOIN
APARTMENT_UTILITY
ON APARTMENT.APARTMENT_ID=APARTMENT_UTILITY.APARTMENT_ID
JOIN APARTMENT_TYPE ON APARTMENT.APARTMENT_TYPE_ID=APARTMENT_TYPE.APARTMENT_TYPE_ID
JOIN UTILITY ON APARTMENT_UTILITY.UTILITY_ID=UTILITY.UTILITY_ID
join apartment on apartment_utility.apartment_id=apartment.apartment_id
WHERE LOWER(APARTMENT_UTILITY.IS_INCLUDED_IN_RENT)= LOWER('YES') AND APARTMENT.MONTHLY_RENT BETWEEN &MIN_RANGE AND &MAX_RANGE;   

SELECT * FROM APARTMENT_UTILITY_DETAILS;


